/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Board() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        FreeParking = new javax.swing.JButton();
        NewYorkAvenue = new javax.swing.JButton();
        TennesseAvenue = new javax.swing.JButton();
        ComunityChest = new javax.swing.JButton();
        JamesPlace = new javax.swing.JButton();
        PennsylvaniaRailroad = new javax.swing.JButton();
        VirginiaAvenue = new javax.swing.JButton();
        StatesAvenue = new javax.swing.JButton();
        ElectricCompany = new javax.swing.JButton();
        CharlesPlace = new javax.swing.JButton();
        Jail = new javax.swing.JButton();
        ConnecticutAvenue = new javax.swing.JButton();
        VermontAvenue = new javax.swing.JButton();
        Chance = new javax.swing.JButton();
        OrientalAvenue = new javax.swing.JButton();
        ReadingRailroad = new javax.swing.JButton();
        IncomeTax = new javax.swing.JButton();
        BalticAvenue = new javax.swing.JButton();
        ComunityChest1 = new javax.swing.JButton();
        MediteraneanAvenue = new javax.swing.JButton();
        Go = new javax.swing.JButton();
        BoardWalk = new javax.swing.JButton();
        LuxuryTax = new javax.swing.JButton();
        ParkPlace = new javax.swing.JButton();
        Chance1 = new javax.swing.JButton();
        ShortLine = new javax.swing.JButton();
        PennsylvaniaAvenue = new javax.swing.JButton();
        ComunityChest2 = new javax.swing.JButton();
        NorthCarolinaAvenue = new javax.swing.JButton();
        PacificAvenue = new javax.swing.JButton();
        GoToJail = new javax.swing.JButton();
        MarvinGardens = new javax.swing.JButton();
        WaterWorks = new javax.swing.JButton();
        VentnorAvenue = new javax.swing.JButton();
        AtlanticAvenue = new javax.swing.JButton();
        BORailroad = new javax.swing.JButton();
        IllinoisAvenue = new javax.swing.JButton();
        IndianaAvenue = new javax.swing.JButton();
        Chance2 = new javax.swing.JButton();
        KentuckyAvenue = new javax.swing.JButton();
        ComunityChestCards = new javax.swing.JButton();
        ChaseCard = new javax.swing.JButton();
        Build = new javax.swing.JButton();
        Sell = new javax.swing.JButton();
        RollDices = new javax.swing.JButton();
        Mortage = new javax.swing.JButton();
        Unmortage = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        SoundOn = new javax.swing.JButton();
        SoundOff = new javax.swing.JButton();
        Tablero = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        FreeParking.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.inactiveBackground"));
        FreeParking.setContentAreaFilled(false);
        FreeParking.setOpaque(false);
        FreeParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreeParkingActionPerformed(evt);
            }
        });
        getContentPane().add(FreeParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        NewYorkAvenue.setContentAreaFilled(false);
        NewYorkAvenue.setOpaque(false);
        NewYorkAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewYorkAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(NewYorkAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 60));

        TennesseAvenue.setContentAreaFilled(false);
        TennesseAvenue.setOpaque(false);
        TennesseAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TennesseAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(TennesseAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 70));

        ComunityChest.setContentAreaFilled(false);
        ComunityChest.setOpaque(false);
        ComunityChest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunityChestActionPerformed(evt);
            }
        });
        getContentPane().add(ComunityChest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 100, 60));

        JamesPlace.setContentAreaFilled(false);
        JamesPlace.setOpaque(false);
        JamesPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamesPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(JamesPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 100, 60));

        PennsylvaniaRailroad.setContentAreaFilled(false);
        PennsylvaniaRailroad.setOpaque(false);
        PennsylvaniaRailroad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PennsylvaniaRailroadActionPerformed(evt);
            }
        });
        getContentPane().add(PennsylvaniaRailroad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 100, 70));

        VirginiaAvenue.setContentAreaFilled(false);
        VirginiaAvenue.setOpaque(false);
        VirginiaAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VirginiaAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(VirginiaAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 100, 60));

        StatesAvenue.setContentAreaFilled(false);
        StatesAvenue.setOpaque(false);
        StatesAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatesAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(StatesAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 100, 60));

        ElectricCompany.setContentAreaFilled(false);
        ElectricCompany.setOpaque(false);
        ElectricCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectricCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(ElectricCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 100, 70));

        CharlesPlace.setContentAreaFilled(false);
        CharlesPlace.setOpaque(false);
        CharlesPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharlesPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(CharlesPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 100, 60));

        Jail.setOpaque(false);
        Jail.setContentAreaFilled(false);
        Jail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailActionPerformed(evt);
            }
        });
        getContentPane().add(Jail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 100, 100));

        ConnecticutAvenue.setContentAreaFilled(false);
        ConnecticutAvenue.setOpaque(false);
        ConnecticutAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnecticutAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(ConnecticutAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 60, 100));

        VermontAvenue.setOpaque(false);
        VermontAvenue.setContentAreaFilled(false);
        VermontAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VermontAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(VermontAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 70, 100));

        Chance.setContentAreaFilled(false);
        Chance.setOpaque(false);
        Chance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChanceActionPerformed(evt);
            }
        });
        getContentPane().add(Chance, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 60, 100));

        OrientalAvenue.setContentAreaFilled(false);
        OrientalAvenue.setOpaque(false);
        OrientalAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrientalAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(OrientalAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 60, 100));

        ReadingRailroad.setContentAreaFilled(false);
        ReadingRailroad.setOpaque(false);
        ReadingRailroad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingRailroadActionPerformed(evt);
            }
        });
        getContentPane().add(ReadingRailroad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 70, 100));

        IncomeTax.setContentAreaFilled(false);
        IncomeTax.setOpaque(false);
        IncomeTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeTaxActionPerformed(evt);
            }
        });
        getContentPane().add(IncomeTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 60, 100));

        BalticAvenue.setContentAreaFilled(false);
        BalticAvenue.setOpaque(false);
        BalticAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalticAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(BalticAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 60, 100));

        ComunityChest.setContentAreaFilled(false);
        ComunityChest.setOpaque(false);
        ComunityChest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunityChest1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComunityChest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 70, 100));

        MediteraneanAvenue.setContentAreaFilled(false);
        MediteraneanAvenue.setOpaque(false);
        MediteraneanAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediteraneanAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(MediteraneanAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 60, 100));

        Go.setContentAreaFilled(false);
        Go.setOpaque(false);
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        getContentPane().add(Go, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 100, 100));

        BoardWalk.setContentAreaFilled(false);
        BoardWalk.setOpaque(false);
        BoardWalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoardWalkActionPerformed(evt);
            }
        });
        getContentPane().add(BoardWalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 100, 70));

        LuxuryTax.setContentAreaFilled(false);
        LuxuryTax.setOpaque(false);
        LuxuryTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuxuryTaxActionPerformed(evt);
            }
        });
        getContentPane().add(LuxuryTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 100, 60));

        ParkPlace.setContentAreaFilled(false);
        ParkPlace.setOpaque(false);
        ParkPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParkPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(ParkPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 100, 60));

        Chance1.setContentAreaFilled(false);
        Chance1.setOpaque(false);
        Chance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chance1ActionPerformed(evt);
            }
        });
        getContentPane().add(Chance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 100, 60));

        ShortLine.setContentAreaFilled(false);
        ShortLine.setOpaque(false);
        ShortLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortLineActionPerformed(evt);
            }
        });
        getContentPane().add(ShortLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 100, 70));

        PennsylvaniaAvenue.setContentAreaFilled(false);
        PennsylvaniaAvenue.setOpaque(false);
        PennsylvaniaAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PennsylvaniaAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(PennsylvaniaAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 100, 60));

        ComunityChest2.setContentAreaFilled(false);
        ComunityChest2.setOpaque(false);
        ComunityChest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunityChest2ActionPerformed(evt);
            }
        });
        getContentPane().add(ComunityChest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 100, 60));

        NorthCarolinaAvenue.setContentAreaFilled(false);
        NorthCarolinaAvenue.setOpaque(false);
        NorthCarolinaAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthCarolinaAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(NorthCarolinaAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 100, 70));

        PacificAvenue.setContentAreaFilled(false);
        PacificAvenue.setOpaque(false);
        PacificAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacificAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(PacificAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 100, 60));

        GoToJail.setContentAreaFilled(false);
        GoToJail.setOpaque(false);
        GoToJail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToJailActionPerformed(evt);
            }
        });
        getContentPane().add(GoToJail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 100, 100));

        MarvinGardens.setContentAreaFilled(false);
        MarvinGardens.setOpaque(false);
        MarvinGardens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarvinGardensActionPerformed(evt);
            }
        });
        getContentPane().add(MarvinGardens, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 70, 100));

        WaterWorks.setContentAreaFilled(false);
        WaterWorks.setOpaque(false);
        WaterWorks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterWorksActionPerformed(evt);
            }
        });
        getContentPane().add(WaterWorks, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 100));

        VentnorAvenue.setContentAreaFilled(false);
        VentnorAvenue.setOpaque(false);
        VentnorAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentnorAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(VentnorAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 100));

        AtlanticAvenue.setContentAreaFilled(false);
        AtlanticAvenue.setOpaque(false);
        AtlanticAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtlanticAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(AtlanticAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 100));

        BORailroad.setContentAreaFilled(false);
        BORailroad.setOpaque(false);
        BORailroad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORailroadActionPerformed(evt);
            }
        });
        getContentPane().add(BORailroad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 100));

        IllinoisAvenue.setContentAreaFilled(false);
        IllinoisAvenue.setOpaque(false);
        IllinoisAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IllinoisAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(IllinoisAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 60, 100));

        IndianaAvenue.setContentAreaFilled(false);
        IndianaAvenue.setOpaque(false);
        IndianaAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndianaAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(IndianaAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 60, 100));

        Chance2.setContentAreaFilled(false);
        Chance2.setOpaque(false);
        Chance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chance2ActionPerformed(evt);
            }
        });
        getContentPane().add(Chance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 70, 100));

        KentuckyAvenue.setContentAreaFilled(false);
        KentuckyAvenue.setOpaque(false);
        KentuckyAvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KentuckyAvenueActionPerformed(evt);
            }
        });
        getContentPane().add(KentuckyAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 60, 100));

        ComunityChestCards.setContentAreaFilled(false);
        ComunityChestCards.setOpaque(false);
        ComunityChestCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunityChestCardsActionPerformed(evt);
            }
        });
        getContentPane().add(ComunityChestCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, 80));

        ChaseCard.setContentAreaFilled(false);
        ChaseCard.setOpaque(false);
        ChaseCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChaseCardActionPerformed(evt);
            }
        });
        getContentPane().add(ChaseCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 140, 90));

        Build.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Build.png"))); // NOI18N
        Build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildActionPerformed(evt);
            }
        });
        getContentPane().add(Build, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 80, 40));

        Sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sell.png"))); // NOI18N
        Sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellActionPerformed(evt);
            }
        });
        getContentPane().add(Sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 80, 40));

        RollDices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RollDices.png"))); // NOI18N
        RollDices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDicesActionPerformed(evt);
            }
        });
        getContentPane().add(RollDices, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 100, 40));

        Mortage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mortage.png"))); // NOI18N
        Mortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MortageActionPerformed(evt);
            }
        });
        getContentPane().add(Mortage, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 100, 40));

        Unmortage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Unmortage.png"))); // NOI18N
        Unmortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnmortageActionPerformed(evt);
            }
        });
        getContentPane().add(Unmortage, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 120, 40));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 80, 40));

        SoundOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sound.png"))); // NOI18N
        SoundOn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        SoundOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundOnActionPerformed(evt);
            }
        });
        getContentPane().add(SoundOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 710, 30, 30));

        SoundOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mute.png"))); // NOI18N
        SoundOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundOffActionPerformed(evt);
            }
        });
        getContentPane().add(SoundOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 710, 30, 30));

        Tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TABLEROF.png"))); // NOI18N
        getContentPane().add(Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FreeParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreeParkingActionPerformed
        //Action who will perform
        JOptionPane.showMessageDialog(null,
            "Plaease fill in both numbers!");
        //The code above is to proove it works rifht
    }//GEN-LAST:event_FreeParkingActionPerformed

    private void NewYorkAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewYorkAvenueActionPerformed
        //code for NewYork Avenue
        //Orange Property
    }//GEN-LAST:event_NewYorkAvenueActionPerformed

    private void TennesseAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TennesseAvenueActionPerformed
        // TODO add your handling code here:
        //Orange Property
        
    }//GEN-LAST:event_TennesseAvenueActionPerformed

    private void ComunityChest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunityChest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunityChest1ActionPerformed

    private void ShortLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShortLineActionPerformed

    private void BuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildActionPerformed

    private void ComunityChestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunityChestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunityChestActionPerformed

    private void JamesPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamesPlaceActionPerformed
        // TODO add your handling code here:
        //Orange Property
    }//GEN-LAST:event_JamesPlaceActionPerformed

    private void PennsylvaniaRailroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PennsylvaniaRailroadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PennsylvaniaRailroadActionPerformed

    private void VirginiaAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VirginiaAvenueActionPerformed
        // TODO add your handling code here:
        //Magenta properties
    }//GEN-LAST:event_VirginiaAvenueActionPerformed

    private void StatesAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatesAvenueActionPerformed
        // TODO add your handling code here:
        //Magenta properties
    }//GEN-LAST:event_StatesAvenueActionPerformed

    private void ElectricCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectricCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElectricCompanyActionPerformed

    private void CharlesPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharlesPlaceActionPerformed
        // TODO add your handling code here:
        //Magenta properties
    }//GEN-LAST:event_CharlesPlaceActionPerformed

    private void JailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JailActionPerformed

    private void ConnecticutAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnecticutAvenueActionPerformed
        // TODO add your handling code here:
        //Light blue properties
    }//GEN-LAST:event_ConnecticutAvenueActionPerformed

    private void VermontAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VermontAvenueActionPerformed
        // TODO add your handling code here:
        //Light blue properties
    }//GEN-LAST:event_VermontAvenueActionPerformed

    private void ChanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChanceActionPerformed

    private void OrientalAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrientalAvenueActionPerformed
        // TODO add your handling code here:
        //Light blue properties
    }//GEN-LAST:event_OrientalAvenueActionPerformed

    private void ReadingRailroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingRailroadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReadingRailroadActionPerformed

    private void IncomeTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncomeTaxActionPerformed

    private void BalticAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalticAvenueActionPerformed
        // TODO add your handling code here:
        //Brown properties
    }//GEN-LAST:event_BalticAvenueActionPerformed

    private void MediteraneanAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediteraneanAvenueActionPerformed
        // TODO add your handling code here:
        //Brown properties
    }//GEN-LAST:event_MediteraneanAvenueActionPerformed

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoActionPerformed

    private void BoardWalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoardWalkActionPerformed
        // TODO add your handling code here:
        //Dark blue properties
    }//GEN-LAST:event_BoardWalkActionPerformed

    private void LuxuryTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuxuryTaxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LuxuryTaxActionPerformed

    private void ParkPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParkPlaceActionPerformed
        // TODO add your handling code here:
        //Dark blue properties
    }//GEN-LAST:event_ParkPlaceActionPerformed

    private void Chance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chance1ActionPerformed

    private void PennsylvaniaAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PennsylvaniaAvenueActionPerformed
        // TODO add your handling code here:
        //Green properties
    }//GEN-LAST:event_PennsylvaniaAvenueActionPerformed

    private void ComunityChest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunityChest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunityChest2ActionPerformed

    private void NorthCarolinaAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthCarolinaAvenueActionPerformed
        // TODO add your handling code here:
        //Green properties
    }//GEN-LAST:event_NorthCarolinaAvenueActionPerformed

    private void PacificAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacificAvenueActionPerformed
        // TODO add your handling code here:
        //Green properties
    }//GEN-LAST:event_PacificAvenueActionPerformed

    private void GoToJailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToJailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoToJailActionPerformed

    private void MarvinGardensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarvinGardensActionPerformed
        // TODO add your handling code here:
        //Yellow properties
    }//GEN-LAST:event_MarvinGardensActionPerformed

    private void WaterWorksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterWorksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaterWorksActionPerformed

    private void VentnorAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentnorAvenueActionPerformed
        // TODO add your handling code here:
        //Yellow properties
    }//GEN-LAST:event_VentnorAvenueActionPerformed

    private void AtlanticAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtlanticAvenueActionPerformed
        // TODO add your handling code here:
        //Yellow properties
    }//GEN-LAST:event_AtlanticAvenueActionPerformed

    private void BORailroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORailroadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BORailroadActionPerformed

    private void IllinoisAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IllinoisAvenueActionPerformed
        // TODO add your handling code here:
        //Red properties
    }//GEN-LAST:event_IllinoisAvenueActionPerformed

    private void IndianaAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndianaAvenueActionPerformed
        // TODO add your handling code here:
        //Red properties
    }//GEN-LAST:event_IndianaAvenueActionPerformed

    private void Chance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chance2ActionPerformed

    private void KentuckyAvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KentuckyAvenueActionPerformed
        // TODO add your handling code here:
        //Red properties
    }//GEN-LAST:event_KentuckyAvenueActionPerformed

    private void ComunityChestCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunityChestCardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunityChestCardsActionPerformed

    private void ChaseCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChaseCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChaseCardActionPerformed

    private void SellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellActionPerformed

    private void MortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MortageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MortageActionPerformed

    private void UnmortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnmortageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnmortageActionPerformed

    private void RollDicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDicesActionPerformed
        // TODO add your handling code here:
        //Code about random numbers for the dices
    }//GEN-LAST:event_RollDicesActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    private void SoundOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundOnActionPerformed

    private void SoundOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtlanticAvenue;
    private javax.swing.JButton BORailroad;
    private javax.swing.JButton BalticAvenue;
    private javax.swing.JButton BoardWalk;
    private javax.swing.JButton Build;
    private javax.swing.JButton Chance;
    private javax.swing.JButton Chance1;
    private javax.swing.JButton Chance2;
    private javax.swing.JButton CharlesPlace;
    private javax.swing.JButton ChaseCard;
    private javax.swing.JButton ComunityChest;
    private javax.swing.JButton ComunityChest1;
    private javax.swing.JButton ComunityChest2;
    private javax.swing.JButton ComunityChestCards;
    private javax.swing.JButton ConnecticutAvenue;
    private javax.swing.JButton ElectricCompany;
    private javax.swing.JButton FreeParking;
    private javax.swing.JButton Go;
    private javax.swing.JButton GoToJail;
    private javax.swing.JButton IllinoisAvenue;
    private javax.swing.JButton IncomeTax;
    private javax.swing.JButton IndianaAvenue;
    private javax.swing.JButton Jail;
    private javax.swing.JButton JamesPlace;
    private javax.swing.JButton KentuckyAvenue;
    private javax.swing.JButton LuxuryTax;
    private javax.swing.JButton MarvinGardens;
    private javax.swing.JButton MediteraneanAvenue;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Mortage;
    private javax.swing.JButton NewYorkAvenue;
    private javax.swing.JButton NorthCarolinaAvenue;
    private javax.swing.JButton OrientalAvenue;
    private javax.swing.JButton PacificAvenue;
    private javax.swing.JButton ParkPlace;
    private javax.swing.JButton PennsylvaniaAvenue;
    private javax.swing.JButton PennsylvaniaRailroad;
    private javax.swing.JButton ReadingRailroad;
    private javax.swing.JButton RollDices;
    private javax.swing.JButton Sell;
    private javax.swing.JButton ShortLine;
    private javax.swing.JButton SoundOff;
    private javax.swing.JButton SoundOn;
    private javax.swing.JButton StatesAvenue;
    private javax.swing.JLabel Tablero;
    private javax.swing.JButton TennesseAvenue;
    private javax.swing.JButton Unmortage;
    private javax.swing.JButton VentnorAvenue;
    private javax.swing.JButton VermontAvenue;
    private javax.swing.JButton VirginiaAvenue;
    private javax.swing.JButton WaterWorks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
